# Generated by Django 3.1.5 on 2021-09-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_likerelations_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeRelations',
            new_name='Like',
        ),
    ]
